const URL='https://tunjhzdeslsliixoepep.supabase.co',KEY='sb_publishable_9d8zAa-nMttJp0n02SyOhg_rvK3ypv-',BUCKET='space-participations',db=supabase.createClient(URL,KEY),$=x=>document.getElementById(x);let cur=JSON.parse(localStorage.getItem('space_user')||'null'),data=JSON.parse(localStorage.getItem('space_records')||'[]'),ship={x:8,y:45},done=new Set();const num=n=>Number(n||0).toLocaleString('ar-SA'),safe=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function need(){if(!cur){alert('أصدري تصريح المهمة أولًا');$('join').scrollIntoView();return false}return true}function act(a){if(!need())return;let r=data.find(x=>x.id===cur.id);if(r&&!r.actions.includes(a))r.actions.push(a);localStorage.setItem('space_records',JSON.stringify(data));sync();render()}
async function sync(){if(!cur)return;let r=data.find(x=>x.id===cur.id);try{await db.from('space_participants').upsert({id:cur.id,name:cur.name,grade:cur.grade,actions:r.actions},{onConflict:'id'})}catch(e){}}
$('register').onclick=()=>{let n=$('name').value.trim(),g=$('grade').value;if(!n||!g)return alert('اكتبي الاسم والصف');cur={id:(crypto.randomUUID?crypto.randomUUID():Date.now()+''),name:n,grade:g};data.push({...cur,actions:[]});localStorage.setItem('space_user',JSON.stringify(cur));localStorage.setItem('space_records',JSON.stringify(data));sync();render()};
function render(){let r=cur&&data.find(x=>x.id===cur.id);$('pass').innerHTML=r?`<p>👩‍🚀 <b>${safe(r.name)}</b> • ${safe(r.grade)} &nbsp; 🚀${r.actions.includes('launch')?'✓':'○'} 🎨${r.actions.includes('design')?'✓':'○'} 🛰️${r.actions.includes('simulation')?'✓':'○'} 🧠${r.actions.includes('challenge')?'✓':'○'} 📸${r.actions.includes('upload')?'✓':'○'}</p>`:'';$('n').textContent=num(data.length);$('l').textContent=num(data.filter(x=>x.actions.includes('launch')).length);$('d').textContent=num(data.filter(x=>x.actions.includes('design')).length);$('s').textContent=num(data.filter(x=>x.actions.includes('simulation')).length);$('q').textContent=num(data.filter(x=>x.actions.includes('challenge')).length);$('u').textContent=num(data.filter(x=>x.actions.includes('upload')).length);$('pioneers').innerHTML=data.length?data.map(x=>`<article>👩‍🚀 <b>${safe(x.name)}</b><p>${safe(x.grade)}</p><div class='badges'>${x.actions.map(a=>`<span>${({launch:'🚀 إطلاق',design:'🎨 تصميم',simulation:'🛰️ محاكاة',challenge:'🧠 تحدي',upload:'📸 مشاركة'})[a]||''}</span>`).join('')}</div></article>`).join(''):'بانتظار أول مشاركة…';let total=data.reduce((s,x)=>s+x.actions.length,0);$('impact').innerHTML=`<div><b>${num(data.length)}</b>مشاركة</div><div><b>${num(data.filter(x=>x.actions.includes('launch')).length)}</b>إطلاق</div><div><b>${num(data.filter(x=>x.actions.includes('design')).length)}</b>تصميم</div><div><b>${num(total)}</b>مهمة منجزة</div>`;let last=data[data.length-1];if(last)$('ticker').textContent=`🚀 ${last.name} • ${last.grade} • ${last.actions.length} مهام منجزة`}
$('rname').oninput=e=>$('rn').textContent=e.target.value||'صاروخي';$('bc').oninput=e=>$('body').style.background=e.target.value;$('nc').oninput=e=>$('nose').style.borderBottomColor=e.target.value;$('wc').oninput=e=>{$('w1').style.background=e.target.value;$('w2').style.background=e.target.value};$('design').onclick=()=>act('design');
$('launch').onclick=async()=>{if(!need())return;for(let i=10;i;i--){$('count').textContent=i;await new Promise(r=>setTimeout(r,300))}$('count').textContent='LIFTOFF!';$('sky').classList.add('fly');$('stage').textContent='الإقلاع ← الصعود ← انفصال المرحلة ← الوصول إلى المدار';setTimeout(()=>{act('launch');$('stage').textContent='🚀 إطلاق ناجح'},4200)};
document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{if(!need())return;let m=b.dataset.m;if(m==='r')ship.x+=12;if(m==='l')ship.x-=12;if(m==='u')ship.y-=10;if(m==='d')ship.y+=10;ship.x=Math.max(2,Math.min(84,ship.x));ship.y=Math.max(5,Math.min(80,ship.y));$('ship').style.left=ship.x+'%';$('ship').style.top=ship.y+'%';if(ship.x>72&&ship.y>30&&ship.y<65){$('sm').textContent='🛰️ تمت المهمة بنجاح!';act('simulation')}});
const qs=[['ما الفرق الذي يذكره الدليل بين الأرض والفضاء؟',['الفضاء لا تتوافر فيه ظروف الحياة الأرضية المعتادة','لا يوجد فرق','الأرض بلا هواء'],0],['أي مما يلي مثال على تقنيات الفضاء؟',['الأقمار الصناعية والمركبات','السبورة','الكتاب فقط'],0],['أي نشاط ورد في الدليل؟',['تصميم وتلوين وتركيب صاروخ','سباق سيارات','طبخ'],0]];$('quiz').innerHTML=qs.map((q,i)=>`<div class='q'><b>${q[0]}</b><div>${q[1].map((a,j)=>`<button onclick='ans(${i},${j},this)'>${a}</button>`).join('')}</div></div>`).join('');window.ans=(i,j,b)=>{if(j===qs[i][2]){b.textContent+=' ✓';done.add(i);if(done.size===qs.length)act('challenge')}else b.textContent+=' ✕'};
window.sheet=(t,icon)=>{$('printarea').innerHTML=`<div class='sheet'><h1>أسبوع الفضاء العالمي ٢٠٢٦</h1><h2>${t}</h2><p>الاسم: __________________ الصف: ________</p><div class='draw'>${icon}</div><p>فكرتي / ملاحظتي: ______________________________________________</p><p>الابتدائية والمتوسطة الأولى بصخيبرة – قطاع الحناكية</p></div>`;print()};
$('upload').onclick=async()=>{if(!need())return;let f=$('photo').files[0];if(!f)return $('us').textContent='اختاري صورة أولًا';if(!f.type.startsWith('image/')||f.size>5*1024*1024)return $('us').textContent='صورة فقط وبحد أقصى 5MB';$('us').textContent='جارٍ الرفع…';try{let p=`${cur.id}/${Date.now()}-${f.name.replace(/[^\w.\-]/g,'_')}`,r=await db.storage.from(BUCKET).upload(p,f);if(r.error)throw r.error;let url=db.storage.from(BUCKET).getPublicUrl(p).data.publicUrl;let ins=await db.from('space_gallery').insert({participant_id:cur.id,name:cur.name,grade:cur.grade,activity:$('act').value,image_url:url});if(ins.error)throw ins.error;act('upload');$('us').textContent='تم رفع المشاركة ✓';gallery()}catch(e){$('us').textContent='يلزم تنفيذ إعداد Supabase المرفق أولًا.'}};
async function gallery(){try{let{data:g}=await db.from('space_gallery').select('*').order('created_at',{ascending:false}).limit(30);if(g)$('gallery').innerHTML=g.map(x=>`<article><img src='${safe(x.image_url)}'><b>${safe(x.name)}</b><p>${safe(x.grade)} • ${safe(x.activity)}</p></article>`).join('')}catch(e){}}
$('lang').onclick=()=>{let en=document.documentElement.lang==='en';document.documentElement.lang=en?'ar':'en';document.documentElement.dir=en?'rtl':'ltr';$('lang').textContent=en?'English':'العربية';document.querySelectorAll('[data-ar]').forEach(x=>x.textContent=en?x.dataset.ar:x.dataset.en)};render();gallery();